### PR TITLE
Fix observable typings when using optional and nullable values

### LINKED ISSUE #151: Optional/nullable properties don't infer types correctly
Given my reading of the [docs](https://legendapp.com/open-source/state/observable/#undefined), having paths to access undefined/null values is valid.

However, this code gives TS errors, presumably because the presence of `undefined` and `null` types makes the type inference break. I have checked that this works as-expected at runtime.

```
const test = observable<{
  optional?: { foo: string };
  nullable: { foo: string } | null;
}>({
  optional: undefined,
  nullable: null,
});

test.optional.foo.set("baz");
// error: 'test.optional' is possibly 'undefined'.
// error: Property 'foo' does not exist on type 'ObservableObject<{ foo: string; } | undefined>'

test.nullable.foo.set("baz");
// error: Property 'foo' does not exist on type 'ObservableObject<{ foo: string; } | null>'
```

Is this expected behaviour? Are there any workarounds?

### PR DESCRIPTION
**Pull request by bram209**
resolves #151

### CODE REVIEW

File: src/observableInterfaces.ts [hunk 1]
```diff
@@ -95,8 +95,8 @@ export interface ListenerParams<T = any> {
 }
 export type ListenerFn<T = any> = (params: ListenerParams<T>) => void;
 
-type PrimitiveKeys<T> = Pick<T, { [K in keyof T]-?: T[K] extends Primitive ? K : never }[keyof T]>;
-type NonPrimitiveKeys<T> = Pick<T, { [K in keyof T]-?: T[K] extends Primitive ? never : K }[keyof T]>;
+type PrimitiveProps<T> = Pick<T, { [K in keyof T]-?: T[K] extends Primitive ? K : never }[keyof T]>;
+type NonPrimitiveProps<T> = Pick<T, { [K in keyof T]-?: T[K] extends Primitive ? never : K }[keyof T]>;
```
Comment (bram209) [inline src/observableInterfaces.ts:99]: I renamed `Keys` to `Props`, because the resulting type represents an object with properties (key-value pairs). `Keys` is therefore a bit misleading imo, but if you want I can rename them back : )

File: src/observableInterfaces.ts [hunk 2]
```diff
@@ -124,14 +124,20 @@ type Recurse<T, K extends keyof T, TRecurse> = T[K] extends ObservableReadable
     ? TRecurse
     : T[K];
 
-type ObservableFnsRecursiveUnsafe<T> = {
-    [K in keyof T]-?: Recurse<T, K, ObservableObject<NonNullable<T[K]>>>;
+type ObservableFnsRecursiveUnsafe<T, NullableMarker> = {
+    [K in keyof T]-?: Recurse<T, K, ObservableObject<T[K], NullableMarker>>;
```
Comment (bram209) [inline src/observableInterfaces.ts:128]: not 100% sure about the name `NullableMarker`, is it clear for you? Open for suggestions...

File: src/observableInterfaces.ts (hunk 1 above)
Comment (jmeistrich) [reply src/observableInterfaces.ts:99]: You're right, that's better 👍

File: src/observableInterfaces.ts (hunk 2 above)
Comment (jmeistrich) [reply src/observableInterfaces.ts:128]: Seems reasonable to me 👍

File: package.json [hunk 3]
```diff
@@ -38,7 +38,8 @@
         "lint:check": "eslint ./src ./tests --ext .ts,.tsx",
         "format:write": "prettier --write \"src/**/*.{js,jsx,ts,tsx}\"",
         "format:check": "prettier --check \"src/**/*.{js,jsx,ts,tsx}\"",
-        "release": "release-it"
+        "release": "release-it",
+        "typecheck": "tsc --noEmit"
```
Comment (bram209) [inline package.json:42]: should I revert this? used it for testing...

File: src/observable.ts [hunk 4]
```diff
@@ -1,22 +1,14 @@
...
 import { NodeValue } from './observableInterfaces';
 
-function createObservable<T>(value: Promise<T>, makePrimitive?: true): ObservablePrimitive<T & PromiseInfo>;
-function createObservable<T>(value?: T, makePrimitive?: true): ObservablePrimitive<T>;
-function createObservable<T>(
-    value?: Promise<T>,
-    makePrimitive?: boolean,
-): ObservablePrimitive<T & PromiseInfo> | ObservableObjectOrArray<T & PromiseInfo>;
-function createObservable<T>(value?: T, makePrimitive?: boolean): ObservablePrimitive<T> | ObservableObjectOrArray<T> {
+type MaybePromise<T> = NonNullable<T> extends Promise<infer U> ? (U & PromiseInfo) | Extract<T, undefined> : T;
```
Comment (bram209) [inline src/observable.ts:7]: I am wondering if we should add variant `PromiseObservable` to the `Observable` union type, so that you could just do `Observable<Promise<Something>>` and it would be able to infer the correct type. 

For now I created a utility type

File: tests/tests.test.ts [hunk 5]
```diff
@@ -2195,7 +2195,7 @@ describe('Promise values', () => {
     test('when callback works with promises', async () => {
         let resolver: (value: number) => void;
         const promise = new Promise<number>((resolve) => (resolver = resolve));
-        const obs = observable<number>(promise);
+        const obs = observable(promise);
```
Comment (bram209) [inline tests/tests.test.ts:2198]: passing the generic type explicitly would have to be done like so: `observable<Promise<number>>(promise);`

we could make it work with `observable<number>(promise);` by adding two function signature overloads to explicitly handle this scenario:
```typescript
export function observable<T>(value: Promise<T>): MaybePromiseObservable<Promise<T>>;
export function observable<T>(value?: Promise<T>): MaybePromiseObservable<Promise<T> | undefined>;
```

not sure if we want that though. For example, in react this would be a type error:
```typescript
useState<number>(Promise.resolve(1));
```

because of `MaybePromise` utility type, the observable still has the correct type, so that:
```typescript
const obs1 = observable(Promise.resolve(10)); // Observable<number & PromiseInfo>
const obs2 = observable(10)); // Observable<number>

File: src/observableInterfaces.ts [hunk 6]
```diff
@@ -316,48 +322,31 @@ export type RecordValue<T> = T extends Record<string, infer t> ? t : never;
...
+type FilterKeysByValue<T, U> = {
+    [K in keyof T]: T[K] extends U ? K & (string | number) : never;
+}[keyof T];
+
+type ObjectKeys<T> = Exclude<FilterKeysByValue<T, Record<string, any>>, FilterKeysByValue<T, any[]>>;
+type DictKeys<T> = FilterKeysByValue<T, Record<string, Record<string, any>>>;
+type ArrayKeys<T> = FilterKeysByValue<T, any[]>;
+type PrimitiveKeys<T> = FilterKeysByValue<T, Primitive>;
+
+export type FieldTransforms<T> =
```
Comment (bram209) [inline src/observableInterfaces.ts:334]: I didn't look into simplifying FieldTransforms yet, as I didn't check how the types are being used.
I think we should (maybe in a separate PR) move the types that have to do with persistence into a separate file, thoughts?

File: package.json (hunk 3 above)
Comment (jmeistrich) [reply package.json:42]: Seems useful to leave it there 👍

File: src/observableInterfaces.ts (hunk 6 above)
Comment (jmeistrich) [reply src/observableInterfaces.ts:334]: Agreed. That file got too long and it would be great to separate the persistence types.

File: tests/tests.test.ts (hunk 5 above)
Comment (jmeistrich) [reply tests/tests.test.ts:2198]: This seems good for now. Let's go more in depth into promises in a follow-up PR based on what we discussed in Slack.

**Comment by jmeistrich** [comment]
Looks great, thank you!
